services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=dockerbaza'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3306:3306'

  springbootappexercise:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: root
